# Generated by Django 5.1.4 on 2025-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('SMM', 'Social Media Meeting'), ('MM', 'Management Meeting')], max_length=50)),
                ('date', models.DateField()),
                ('agenda', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('target_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('staff_members', models.ManyToManyField(to='Management.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('task_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Q&A', 'Q&A'), ('Giveaway', 'Giveaway'), ('Ladies Night', 'Ladies Night'), ('Other', 'Other')], max_length=50)),
                ('delegation_notes', models.TextField(blank=True, null=True)),
                ('publishing_date', models.DateField(blank=True, null=True)),
                ('staff_members', models.ManyToManyField(to='Management.staff')),
            ],
        ),
    ]
