# Generated by Django 5.1.4 on 2025-01-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delegation_notes',
        ),
    ]
