# Generated by Django 5.1.4 on 2025-01-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_task_publishing_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='publishing_date',
        ),
    ]
