# Generated by Django 5.1.4 on 2025-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_target_target_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='staff_members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='staff_members',
        ),
        migrations.AddField(
            model_name='target',
            name='staff_members',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='staff_members',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
