# Generated by Django 5.1.4 on 2025-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_remove_target_staff_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Q&A', 'Q&A'), ('Giveaway', 'Giveaway'), ('Ladies Night', 'Ladies Night'), ('Other', 'Other')], default='Commercial', max_length=50),
            preserve_default=False,
        ),
    ]
