# Generated by Django 5.1.4 on 2025-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Q&A', 'Q&A'), ('Giveaway', 'Giveaway'), ('Ladies Night', 'Ladies Night'), ('Events', 'Events')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Q&A', 'Q&A'), ('Giveaway', 'Giveaway'), ('Ladies Night', 'Ladies Night'), ('Events', 'Events')], max_length=50),
        ),
    ]
