# Generated by Django 5.1.4 on 2025-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_customer_contact_alter_arcadefeedback_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(max_length=500)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=15)),
                ('area_of_residence', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
