# Generated by Django 5.1.4 on 2025-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='Management.staffroles'),
        ),
    ]
