# Generated by Django 5.1.4 on 2025-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_staffroles_remove_staffprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffroles',
            name='role',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Q&A', 'Q&A'), ('Giveaway', 'Giveaway'), ('Ladies Night', 'Ladies Night'), ('Events', 'Events')], max_length=50),
        ),
    ]
