# Generated by Django 5.1.4 on 2025-01-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_alter_staffprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='area_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
