# Generated by Django 5.1.4 on 2025-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liability',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
