# Generated by Django 5.1.4 on 2025-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.DecimalField(decimal_places=2, max_digits=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(blank=True, max_length=500, null=True)),
                ('cafe_sales', models.DecimalField(decimal_places=2, max_digits=13)),
                ('arcade_sales', models.DecimalField(decimal_places=2, max_digits=13)),
                ('cafe_expenses', models.DecimalField(decimal_places=2, max_digits=13)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
