# Generated by Django 5.1.4 on 2025-01-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='event',
            new_name='Event',
        ),
        migrations.AddField(
            model_name='sale',
            name='event_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('quantity_on_hand', models.FloatField()),
                ('minimum_stock_level', models.FloatField()),
                ('maximum_stock_level', models.FloatField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(max_length=255)),
                ('restock_needed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
