# Generated by Django 5.1.4 on 2025-01-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_rename_event_sale_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='code',
            new_name='Event',
        ),
        migrations.AddField(
            model_name='sale',
            name='ladies_night',
            field=models.BooleanField(default=False),
        ),
    ]
