# Generated by Django 5.1.4 on 2025-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_rename_code_sale_event_sale_ladies_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='event_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
    ]
